name: Build

on:
  workflow_dispatch:
    inputs:
      jdk_distribution:
        description: JDK Distribution
        required: true
        type: choice
        default: "openjdk"
        options:
          - "openjdk"
          - "corretto"
      jdk_version:
        description: JDK Version
        required: true
        type: choice
        options:
          - 21

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    env:
      JDK_DISTRIBUTION: ${{ github.event.inputs.jdk_distribution }}
      JDK_VERSION: ${{ github.event.inputs.jdk_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Install cygwin on Windows
        uses: cygwin/cygwin-install-action@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          packages: gcc-core,mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,mingw64-x86_64-glib2.0,make,autoconf,zip,unzip
      - name: Install Boot JDK
        uses: actions/setup-java@v3
        if: ${{ github.event.inputs.jdk_distribution != 'openjdk' }}
        with:
          distribution: ${{ github.event.inputs.jdk_distribution }}
          java-version: ${{ github.event.inputs.jdk_version }}
      - name: Build on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: | 
          cd "$GITHUB_WORKSPACE/main"
          ./scripts/build-ubuntu.sh
      - name: Build on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd "$GITHUB_WORKSPACE/main"
          ./scripts/build-macos.sh
      - name: Build on Windows
        shell: pwsh
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd "$env:GITHUB_WORKSPACE\main"
          Powershell.exe -File scripts\build-windows.ps1
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hsdis-${{ github.event.inputs.jdk_distribution }}-${{ github.event.inputs.jdk_version }}-${{ matrix.os }}
          path: ${{ env.HSDIS_BUILD_ARTIFACT_PATH }}
