name: Build

on:
  workflow_dispatch:
    inputs:
      jdk_name:
        description: JDK Name
        required: true
        type: choice
        default: "OpenJDK"
        options:
          - "OpenJDK"
          - "Amazon Corretto"
      jdk_version:
        description: JDK Version
        required: true
        type: choice
        options:
          - 21

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    env:
      JDK_NAME: ${{ github.event.inputs.jdk_name }}
      JDK_VERSION: ${{ github.event.inputs.jdk_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Build on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: | 
          cd "$GITHUB_WORKSPACE/main"
          ./scripts/build-ubuntu.sh
      - name: Build on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd "$GITHUB_WORKSPACE/main"
          ./scripts/build-macos.sh
      - name: Build on Windows
        shell: pwsh
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd "$env:GITHUB_WORKSPACE\main"
          Powershell.exe -File scripts\build-windows.ps1
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hsdis-${{ matrix.os }}
          path: ${{ env.HSDIS_BUILD_ARTIFACT_PATH }}
